import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { config, publicUrl, type ServiceRecord } from "../config.js";
import type { IntegrationResult } from "./pihole.js";

function siteBlock(service: ServiceRecord): string {
  const upstream = `${service.protocol === "https" ? "https" : "http"}://${service.ip}${
    service.port ? `:${service.port}` : ""
  }`;
  const tlsVerify =
    service.protocol === "https"
      ? "\n\t\ttransport http {\n\t\t\ttls_insecure_skip_verify\n\t\t}"
      : "";

  return `${service.hostname} {
\ttls internal
\treverse_proxy ${upstream} {${tlsVerify}
\t}
}
`;
}

export function renderCaddySnippet(services: ServiceRecord[]): string {
  const proxied = services.filter((s) => s.proxy && !s.paused);
  const header = `# Generated by ArpaDashboard — do not edit by hand
# Import from your Caddyfile, e.g.:
#   import /path/to/arpa-dashboard.caddy
#
`;
  if (proxied.length === 0) {
    return `${header}# (no proxied services)\n`;
  }
  return header + proxied.map(siteBlock).join("\n");
}

export async function syncCaddySnippet(
  services: ServiceRecord[],
): Promise<IntegrationResult> {
  if (!config.caddySnippetPath) {
    return {
      ok: true,
      skipped: true,
      detail: "Caddy snippet path not configured (set CADDY_SNIPPET_PATH)",
    };
  }

  if (config.dryRunIntegrations) {
    return {
      ok: true,
      skipped: true,
      detail: `dry-run: would write ${config.caddySnippetPath}`,
    };
  }

  const file = path.resolve(config.caddySnippetPath);
  await mkdir(path.dirname(file), { recursive: true });
  const body = renderCaddySnippet(services);
  await writeFile(file, body, "utf8");

  return {
    ok: true,
    detail: `Wrote Caddy snippet (${services.filter((s) => s.proxy && !s.paused).length} sites) → ${file}`,
  };
}

export function dashboardPayload(services: ServiceRecord[]) {
  return services.map((s) => ({
    ...s,
    href: publicUrl(s),
  }));
}
